#
#spring:
#  data:
#    mongodb:
#      uri: mongodb+srv://admin:admin@nedcluster.wnvsxlc.mongodb.net/?retryWrites=true&w=majority
#      database: blogapp


  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/blogapp
      username: root
      password:
    jpa:
      hibernate:
        ddl-auto: update




