
spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@nedcluster.wnvsxlc.mongodb.net/?retryWrites=true&w=majority
      database: blogapp

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

